### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nsavageJVM** [pablo-tech/hedge-fund-learner#1]
Exception in thread "main" java.lang.NoSuchMethodError:

      <artifactId>spark-core_2.10</artifactId>

      <artifactId>spark-streaming-kinesis-asl_2.11</artifactId>

their is a big jump from spark 2.10 to spark 2.11
I would give this a try

<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-streaming-kinesis-asl_2.10</artifactId>
	<version>1.5.1</version>
</dependency>

**Comment by pablo-tech** [comment]
so move to 2.11 is your suggestion? Is KinesisUtils still the way to stream data from kinesis?

**Comment by nsavageJVM** [comment]
Hi 
I saw your post where you mentioned   java.lang.NoSuchMethodError exception

their are theses scala dependencies 
    compile 'org.scala-lang:scala-library:2.11.0'
    compile 'org.scala-lang:scala-library:2.10.0'

in my experience you get these errors when you mix them so

 <artifactId>spark-core_2.10</artifactId>
  <artifactId>spark-streaming-kinesis-asl_2.10</artifactId> 

or

 <artifactId>spark-core_2.11</artifactId>
  <artifactId>spark-streaming-kinesis-asl_2.11</artifactId>

this may not fix your error however it will improve the dependency graph

also did you set up the IAM policies for the cluster and Kinesis?  this will have to be done I think

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-set-iam-policy.html

Is KinesisUtils still the way to stream data from kinesis?

I understand why you ask this, AWD have made it mandatory to set up  IAM policies for new accounts after June this year, I ran into this setting up a EMR cluster 2 weeks ago, the documentation is still in a state of flux.

This is what I know for sure
1 the emr cluster (EC2 boxes) security group/keys/settings must be in the same region as the input output artefacts
2. Kinesis is a message broker these streams start at producers and stream to consumers via brokers, so I would expect that you will need to set up IAM policies for every artefact in the producer to consumer chain, I think this includes dynamoBb
3. I was getting exceptions for my input and output streams for my emr cluster and the errors/stack-trace did not point to the IAM policies issues I mention in 2.

The point I am trying to elaborate here is your spark code could be correct but due to security errors in the stream prod/brok/consum chain artefacts as a result of incorrect IAM policy settings you may see these as unrelated errors in the Spark/EMR stack trace

I am going to set up spark streaming next in my dev project
https://github.com/nsavageJVM/spark-dev

what I will do is set up a mock stream  producer and get the basic Spark analytic code working as a test first, then ramp up the velocity of the mock producer









looking at the code the spark-core_2.10 uses spark/scala api that is different to  2.11, in my experience there afre many issues with

**Comment by pablo-tech** [comment]
@nsavageJVM fabulous thank you so much! I will go the IAM route, it sounds like the errors I am seen could be unrelated
